# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu_server" do |ubuntu|
    ubuntu.vm.box = "ubuntu/focal64"
    ubuntu.vm.host_name = "ubuntu"
    ubuntu.vm.provider:virtualbox do |vb|
      vb.name="Ubuntu_Server"
    end
    ubuntu.vm.synced_folder '.', '/vagrant', disabled: true
  end
end
